# Generated by Django 3.2 on 2021-04-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210426_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.TextField(choices=[('Fashion', 'Fashion'), ('Toys', 'Toys'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Books', 'Books')], default='books'),
            preserve_default=False,
        ),
    ]
